services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cineuser
      POSTGRES_PASSWORD: cinepass
      POSTGRES_DB: cinetheque
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cineuser -d cinetheque"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: postgresql://cineuser:cinepass@db:5432/cinetheque
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: