version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: cineuser
      POSTGRES_PASSWORD: cinepass
      POSTGRES_DB: cinetheque
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5433:5432" 
    environment:
      DATABASE_URL: postgresql://cineuser:cinepass@db:5432/cinetheque
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata: